
server:
 port: 8888
 
spring: 
 cloud:
  config:
   server:
    git:
     uri: /home/mateuslourenco/eclipse-workspace/e-commerce-microservices
    # uri: https://github.com/mateus-lourenco/e-commerce-microservices
